apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
    version: "2.60.1"
spec:
  type: NodePort
  selector:
    app: myjavaapp
    version: "2.60.1"
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
